#!/bin/bash
SRC=/data/S2E/packages/s2e_recon/EMC_Src
INPUT=/data/S2E/data/sim_example/diffr
TMP=/data/S2E/tmp
OUTPUT=/data/S2E/data/sim_example
PWD=`pwd`

INITIALQUAT=5
MAXQUAT=9
MAXITER=200
MINERR="4.E-8"
PLOT=1
DETAILED=1

SLEEPDUR=60
NUMRECON=1
#Compiles exectuables in the SRC directory; 
#needed for runEMC.py script.
cd ${SRC}
./compile_EMC
cd ${PWD}

#Let's parse some options.
OPTS="-s ${SRC} -T ${TMP} -i ${INPUT} -o ${OUTPUT} -q ${INITIALQUAT} -Q ${MAXQUAT} -m ${MAXITER} -e ${MINERR} "
ADDOPT=" "
[$PLOT -eq 1] && {ADDOPT="${ADDOPT} -p"} 
[$DETAILED -eq 1] && {ADDOPT="${ADDOPT} -d"}
OPTS="${OPTS} ${ADDOPT}"

#Starts multiple reconstructions 
for i in `seq 1 ${NUMRECON}`;
do
    echo "Starting reconstruction ${i}."
    echo "Temporary output stored in ${TMP}."
    echo "Output stored in ${OUTPUT}."
	nohup python runEMC.py ${OPTS} &
	sleep ${SLEEPDUR}
done
