#!/bin/bash
SRC=/mnt/cbis/images/duaneloh/S2E/gold_example/s2e_recon/DM_Src
TMP=/mnt/cbis/images/duaneloh/S2E/gold_example/phasing
INPUT=/mnt/cbis/images/duaneloh/S2E/gold_example/tmp
OUTPUT=/mnt/cbis/images/duaneloh/S2E/gold_example/tmp
PWD=`pwd`

NUMTRIALS=500
STARTAVE=15
NUMITER=50
LEASH=0.2
SHRINKCYCLES=10

SLEEPDUR=60
NUMRECON=1

#Compiles exectuables in the SRC directory; 
#needed for runDM.py script.
cd ${SRC}
./compile_DM
cd ${PWD}
   
#Starts multiple reconstructions 
for i in `seq 1 ${NUMRECON}`;
do
    echo "Starting reconstruction ${i}."
    nohup python runDM.py -s ${SRC} -T ${TMP} -i ${INPUT} -o ${OUTPUT} -r ${NUMTRIALS} -a ${STARTAVE} -n ${NUMITER} -l ${LEASH} -c ${SHRINKCYCLES} &
	sleep ${SLEEPDUR}
done
