#!/bin/bash
SRC=/data/S2E/packages/s2e_recon/DM_Src
TMP=/data/S2E/tmp
INPUT=/data/S2E/data/sim_example
OUTPUT=/data/S2E/data/sim_example
PWD=`pwd`

NUMTRIALS=500
STARTAVE=15
NUMITER=50
LEASH=0.2
SHRINKCYCLES=10

SLEEPDUR=60
NUMRECON=1

#Compiles exectuables in the SRC directory; 
#needed for runDM.py script.
cd ${SRC}
./compile_DM
cd ${PWD}
   
#Starts multiple reconstructions 
for i in `seq 1 ${NUMRECON}`;
do
    echo "Starting reconstruction ${i}."
    nohup python runDM.py -s ${SRC} -T ${TMP} -i ${INPUT} -o ${OUTPUT} -t ${NUMTRIALS} -a ${STARTAVE} -n ${NUMITER} -l ${LEASH} -c ${SHRINKCYCLES} &
	sleep ${SLEEPDUR}
done
